/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2022-12-03 10:34:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\" />\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\r\n");
      out.write("    <meta name=\"description\" content=\"Responsive Admin Dashboard Template\" />\r\n");
      out.write("    <meta name=\"keywords\" content=\"admin,dashboard\" />\r\n");
      out.write("    <meta name=\"author\" content=\"stacks\" />\r\n");
      out.write("    <!-- The above 6 meta tags *must* come first in the head; any other head content must come *after* these tags -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Title -->\r\n");
      out.write("    <title>Erudite - Login Page</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Styles -->\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" />\r\n");
      out.write("    <link\r\n");
      out.write("            href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap\"\r\n");
      out.write("            rel=\"stylesheet\"\r\n");
      out.write("    />\r\n");
      out.write("    <link\r\n");
      out.write("            href=\"https://fonts.googleapis.com/css2?family=Montserrat:wght@100;300;400;500;600;700;800&display=swap\"\r\n");
      out.write("            rel=\"stylesheet\"\r\n");
      out.write("    />\r\n");
      out.write("    <link\r\n");
      out.write("            href=\"https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Two+Tone|Material+Icons+Round|Material+Icons+Sharp\"\r\n");
      out.write("            rel=\"stylesheet\"\r\n");
      out.write("    />\r\n");
      out.write("    <link\r\n");
      out.write("            href=\"http://localhost/assets/plugins/bootstrap/css/bootstrap.min.css\"\r\n");
      out.write("            rel=\"stylesheet\"\r\n");
      out.write("    />\r\n");
      out.write("    <link\r\n");
      out.write("            href=\"http://localhost/assets/plugins/perfectscroll/perfect-scrollbar.css\"\r\n");
      out.write("            rel=\"stylesheet\"\r\n");
      out.write("    />\r\n");
      out.write("    <link href=\"http://localhost/assets/plugins/pace/pace.css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("    <!-- Theme Styles -->\r\n");
      out.write("    <link href=\"http://localhost/assets/css/main.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("    <link href=\"http://localhost/assets/css/custom.css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("    <link\r\n");
      out.write("            rel=\"icon\"\r\n");
      out.write("            type=\"image/png\"\r\n");
      out.write("            sizes=\"32x32\"\r\n");
      out.write("            href=\"http://localhost/assets/images/neptune.png\"\r\n");
      out.write("    />\r\n");
      out.write("    <link\r\n");
      out.write("            rel=\"icon\"\r\n");
      out.write("            type=\"image/png\"\r\n");
      out.write("            sizes=\"16x16\"\r\n");
      out.write("            href=\"http://localhost/assets/images/neptune.png\"\r\n");
      out.write("    />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div\r\n");
      out.write("        class=\"app app-auth-sign-in align-content-stretch d-flex flex-wrap justify-content-end\"\r\n");
      out.write(">\r\n");
      out.write("    <div class=\"app-auth-background\"></div>\r\n");
      out.write("    <div class=\"app-auth-container\">\r\n");
      out.write("        <div class=\"logo\">\r\n");
      out.write("            <a href=\"index.html\">Erudite</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <p class=\"auth-description\">\r\n");
      out.write("            Please sign-in to your account and continue to the dashboard.<br />Don't\r\n");
      out.write("            have an account? <a href=\"sign-up.html\">Sign Up</a>\r\n");
      out.write("        </p>\r\n");
      out.write("        \r\n");
      out.write("        ");
 
        
        if(session.getAttribute("error") != null){
        	out.print(session.getAttribute("error"));
        	session.setAttribute("error",null);
        }
        
        
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<form action=\"handler/handler_login.jsp\" method=\"POST\">\r\n");
      out.write("        <div class=\"auth-credentials m-b-xxl\">\r\n");
      out.write("            <label for=\"signInEmail\" class=\"form-label\">Email address</label>\r\n");
      out.write("            <input\r\n");
      out.write("            \t\tname=\"email\"\r\n");
      out.write("                    type=\"email\"\r\n");
      out.write("                    class=\"form-control m-b-md\"\r\n");
      out.write("                    id=\"signInEmail\"\r\n");
      out.write("                    aria-describedby=\"signInEmail\"\r\n");
      out.write("                    placeholder=\"example@neptune.com\"\r\n");
      out.write("            />\r\n");
      out.write("\r\n");
      out.write("            <label for=\"signInPassword\" class=\"form-label\">Password</label>\r\n");
      out.write("            <input\r\n");
      out.write("            \t\tname=\"password\"\r\n");
      out.write("                    type=\"password\"\r\n");
      out.write("                    class=\"form-control\"\r\n");
      out.write("                    id=\"signInPassword\"\r\n");
      out.write("                    aria-describedby=\"signInPassword\"\r\n");
      out.write("                    placeholder=\"&#9679;&#9679;&#9679;&#9679;&#9679;&#9679;&#9679;&#9679;\"\r\n");
      out.write("            />\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"auth-submit\">\r\n");
      out.write("            <button type=\"submit\" class=\"btn btn-primary\">Sign In</button>\r\n");
      out.write("            <a href=\"#\" class=\"auth-forgot-password float-end\"\r\n");
      out.write("            >Forgot password?</a\r\n");
      out.write("            >\r\n");
      out.write("        </div>\r\n");
      out.write("        </form>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"divider\"></div>\r\n");
      out.write("        <div class=\"auth-alts\">\r\n");
      out.write("            <a href=\"#\" class=\"auth-alts-google\"></a>\r\n");
      out.write("            <a href=\"#\" class=\"auth-alts-facebook\"></a>\r\n");
      out.write("            <a href=\"#\" class=\"auth-alts-twitter\"></a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Javascripts -->\r\n");
      out.write("<script src=\"http://localhost/assets/plugins/jquery/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("<script src=\"http://localhost/assets/plugins/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"http://localhost/assets/plugins/perfectscroll/perfect-scrollbar.min.js\"></script>\r\n");
      out.write("<script src=\"http://localhost/assets/plugins/pace/pace.min.js\"></script>\r\n");
      out.write("<script src=\"http://localhost/assets/js/main.min.js\"></script>\r\n");
      out.write("<script src=\"http://localhost/assets/js/custom.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
